# Generated by Django 4.0.4 on 2022-05-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='mail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sender', models.TextField()),
                ('recipient', models.TextField()),
                ('subject', models.TextField()),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
    ]
